#!/bin/bash
# Live2D Viewerをビルドしてapp/assetsに配置するスクリプト

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
VIEWER_DIR="$PROJECT_ROOT/live2d-viewer"
APP_ASSETS_DIR="$PROJECT_ROOT/app/assets"
APP_CONSTANTS_DIR="$PROJECT_ROOT/app/src/constants"

echo "=== Live2D Viewer Build ==="

# 1. live2d-viewerディレクトリに移動してビルド
echo "[1/3] Building live2d-viewer..."
cd "$VIEWER_DIR"
npm install
npm run build

# 2. ビルド成果物をapp/assetsにコピー
echo "[2/3] Copying build output to app/assets..."
cp "$VIEWER_DIR/dist/index.html" "$APP_ASSETS_DIR/live2d-viewer.html"

# 3. TypeScriptモジュールとしてラップ（Node.jsで安全にエスケープ）
echo "[3/3] Generating TypeScript module..."
node -e "
const fs = require('fs');
const html = fs.readFileSync('$APP_ASSETS_DIR/live2d-viewer.html', 'utf-8');
const ts = '// Auto-generated by build-viewer.sh - DO NOT EDIT\nexport const LIVE2D_VIEWER_HTML: string = ' + JSON.stringify(html) + ';\n';
fs.writeFileSync('$APP_CONSTANTS_DIR/live2d-viewer-html.ts', ts);
"

echo "=== Build Complete ==="
echo "  HTML: $APP_ASSETS_DIR/live2d-viewer.html"
echo "  TS:   $APP_CONSTANTS_DIR/live2d-viewer-html.ts"
